apiVersion: v1
kind: Service
metadata:
  name: container2-service
spec:
  type: LoadBalancer
  selector:
    app: container2
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2
  labels:
    app: container2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
        - name: container2
          image: us-central1-docker.pkg.dev/dotted-rookery-390001/cont2-docker/cont2-image:latest
          ports:
            - containerPort: 9000
          imagePullPolicy: Always
          volumeMounts:
            - name: test-pv-storage
              mountPath: "/kush_PV_dir"    
      volumes:
        - name: test-pv-storage
          persistentVolumeClaim:
            claimName: test-pv-claim